server:
  port: 80

spring:
  config:
    activate:
      on-profile: prod # 환경이름설정
  mvc:
    static-path-pattern: /static/**
  resources:
    static-location: classpath:/static/
    add-mapping: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://192.168.1.19:5432/reserve_db
    username: reserve_manager
    password: levware!1234